### ISSUE TITLE
Deploy via Azure DevOps

### ISSUE THREAD

**Issue by sonphnt** [microsoft/azurechat#289]
Hi, Has anyone deployed successfully by using Azure DevOps pipeline with yml file? Thanks a lot.

**Comment by n3662** [comment]
@sonphnt 

Here is the yml file for our devops Pipeline

```yaml
# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  pipelines:
    - pipeline: Azure Chat GPT-CI # Name of the pipeline resource.
      source: Azure Chat GPT-CI # The name of the pipeline referenced by this pipeline resource.
      trigger: true

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      cd ./src
      npm install
      npm run build
      cd ..
      cp -R ./src/.next/standalone ./site-deploy
      cp -R ./src/.next/static ./site-deploy/.next/static
      cp -R ./src/public ./site-deploy/public
      cd ./site-deploy
      zip Nextjs-site.zip ./* .next -qr
    displayName: "yarn install and build"

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: "AzureRM"
      azureSubscription: "azure-sub-connection"
      appType: "webAppLinux"
      WebAppName: "your-web-app"
      packageForLinux: "$(System.DefaultWorkingDirectory)/**/*.zip"
      RuntimeStack: "NODE|18-lts"
```
